### ISSUE TITLE
[backend]Create Info controller

### ISSUE THREAD

**Issue by teruto725** [ani-hovhannisyan/kanji-visualization#48] opened 2022-02-04 05:38 UTC
Create Info controller
```
Class Info controller
offer only get_kanji_info function
- Input: kanji (ex 山)
- Output: dictionary (ex { “onyomi”: san, “kunyomi”: yama})
- Additional you can: return english meaning also
- 
```

**Comment by TakumiHiraide** [comment] 2022-02-04 07:21
I report about the error.
I installed requirements.txt that includes jamdict by "pip install -r ./backend/requirements.txt".
However,  backend/Infocontroller.py doesn't work. The error is below.
File "/Users/takumi-hi/kanji-visualization/kanji-visualization/backend/InfoController.py", line 3, in <module>
    from jamdict import Jamdict
ModuleNotFoundError: No module named 'jamdict'

**Comment by TakumiHiraide** [comment] 2022-02-04 07:31
The code InfoController.py is below.
#pip install jamdict jamdict-data
from jamdict import Jamdict
class InfoController:
    #from jamdict import Jamdict
    def get_jamdict_data():
        jam = Jamdict()
        print("query: ", end="")
        query = input()
        result = jam.lookup(query)
        index = -1
        print(result)
get_jamdict_data()

**Comment by wowry** [comment] 2022-02-04 08:25
@TakumiHiraide 
Sorry, the current `. /backend/requirements.txt` contains only the libraries that were needed to build the development environment, so please add more libraries as needed.
In this case, please run `pip install jamdict jamdict-data` on your terminal, and edit `./backend/requirements.txt` as follows:
```py:requirements.txt
flake8
black
mypy
pytest
pre-commit
fastapi
uvicorn
jamdict
jamdict-data
```

This will ensure that the latest dependent libraries are installed when others run `pip install -r ./backend/requirements.txt`.

**Comment by TakumiHiraide** [comment] 2022-02-04 09:25
Sorry, I did what you said, but it still doesn't work. Maybe I have another problem.

**Comment by TakumiHiraide** [comment] 2022-02-04 09:27
The error is same
from jamdict import Jamdict
ModuleNotFoundError: No module named 'jamdict'

**Comment by wowry** [comment] 2022-02-04 10:41
@TakumiHiraide 
By the way, can you run this file without errors?
https://gist.github.com/wowry/840715df27d75171c5a8456e76275862

**Comment by TakumiHiraide** [comment] 2022-02-04 10:57
No, not yet because  the first "from jamdict import Jamdict" throws an error "ModuleNotFoundError: No module named 'jamdict' ".

**Comment by wowry** [comment] 2022-02-04 11:05
@TakumiHiraide 
OK, then please run `pip list` and check the list contains the libraries you expected.

![image](https://user-images.githubusercontent.com/35371161/152518550-09d84480-e3b0-4c92-863b-8c0ea1fa0708.png)

**Comment by TakumiHiraide** [comment] 2022-02-04 11:13
I made sure that list contained "jamdict and jamdict-data"
![スクリーンショット 2022-02-04 20 10 52](https://user-images.githubusercontent.com/84693250/152519328-17d99a11-e317-4d01-94af-6a838f278c93.png)

**Comment by TakumiHiraide** [comment] 2022-02-04 11:27
Does it work for you?

**Comment by TakumiHiraide** [comment] 2022-02-04 11:52
My folder structure is here. I want to run "InfoController.py" which is same to "sample_jamdict.py"

![スクリーンショット 2022-02-04 20 49 41](https://user-images.githubusercontent.com/84693250/152524359-d570d916-0169-4db9-9d96-0bb874fdfff0.png)

**Comment by wowry** [comment] 2022-02-04 12:26
Hmm... It looks strange (because `kanji-visualization` in `kanji-visualization`), but there seems to be no problem.
Yes, it works in my local environment.
Could you send me the screenshot of your `InfoController.py`?

**Comment by TakumiHiraide** [comment] 2022-02-04 13:16
I think this is completely the same "sample_jamdict.py" you prepare.
![スクリーンショット 2022-02-04 22 11 09](https://user-images.githubusercontent.com/84693250/152535000-762f3c14-cdea-4e71-931c-1e36ac2c715c.png)

**Comment by ani-hovhannisyan** [comment] 2022-02-04 13:28
Ok so may I summarize? As far as I understood, we still didn't understand where isn't visible the jamdict module, in your local machine? or in VisualStudio terminal environment? I just tried same and it worked on my machine so from my understanding to have nested directories isn't good, because you have now 2 git repositories nested each other, as said @wowry the kanji-visualization directory is nested in KANJI-VISUALIZATION directory. 
**TEST ENVIRONMENT**
Can you do this to check if jamdict is working in whole computer?
Step 1. Open new terminal without visual studio code and type:
   $ python3
Step 2. Now  type:
    `from jamdict import Jamdict`
Step 3. if you see nothing is printed after 2nd step then jamdict worked! That means the problem is that you have nested directories, MAYBE! Please try to make one directory with one .github directory inside (not nested).
 But if it 2nd step says can't find .... then jamdict isn't installed in your local machine.
 
 To fix that at this point and to continue coding, you can open again new terminal and type same as @wowry saidOk :
  $ pip install jamdict jamdict-data  (I guess as you see the pip list this won't be the case now)
 
**TEST CODE**
 But if you want to make sure if simple jamdict code will work try this testing steps:
1. Open new terminal and type:
  $ ` cd ~/; mkdir test-jamdict; cd test-jamdict; touch jd.py`
2. Now just open the jd.py file from test-jamdict folder and paste this code:
```
from jamdict import Jamdict
jam = Jamdict()
result = jam.lookup('食べ%る')
for entry in result.entries:
    print(entry)
for c in result.chars:
    print(repr(c))
print("If you see this message them JAMDICT WORKED in your computer !!!")

```
3. Now go back to the same terminal and type
 $ `python3 jd.py`
4. Now you should see the printed last message
5. OPTIONAL. Now go to your project directory then open terminal and do the same as from TEST CODE ?

**Comment by wowry** [comment] 2022-02-04 13:33
That's exactly what I want to say!

**Comment by ani-hovhannisyan** [comment] 2022-02-04 13:35
> That's exactly what I want to say!

Sorry for stoling your thoughts ))) I saw many emails coming from this issue and checked in my side then typed same steps as I did in my machine ^^

**Comment by wowry** [comment] 2022-02-04 13:37
Nice, thank you very much for your support!

**Comment by TakumiHiraide** [comment] 2022-02-04 15:09
Everyone, thank you so much. I fixed nested directories, but it doesn't work. So, I use terminal application, then I don't know why, but it worked.
![スクリーンショット 2022-02-05 0 08 52](https://user-images.githubusercontent.com/84693250/152552663-80add8a1-6123-40f5-9c82-f5d37174a04f.png)
.

**Comment by wowry** [comment] 2022-02-04 16:19
Maybe following the steps in the link below will be solve this error, but yes, we don't have much time this week as ani san said, so don't think too much! :)

https://qiita.com/Toyoizumi-Hiroyuki/items/db8709e3dd821750d570#python%E5%AE%9F%E8%A1%8C%E7%92%B0%E5%A2%83%E3%81%AE%E8%A8%AD%E5%AE%9A

**Comment by TakumiHiraide** [comment] 2022-02-09 01:19
I made InfoController, but "kanji_info" and "error_info" are list type. Is it OK? I'm not sure if this will be reflected in the frontend.

![スクリーンショット 2022-02-09 10 15 49](https://user-images.githubusercontent.com/84693250/153103173-78db757a-895a-4490-b471-a878d2f19e3b.png)

![スクリーンショット 2022-02-09 10 14 24](https://user-images.githubusercontent.com/84693250/153103512-8fa0b84c-5503-45fc-a79c-ccd7cc52122e.png)

**Comment by teruto725** [comment] 2022-02-09 05:03
It's not good.
You should use dictionary instead of list.
you chan just fix likes below.
```
kanji_info = {"onyomi":yomi, "meaning", meaning} 
```
and kanji info is also needed kunyomi right?

**Comment by TakumiHiraide** [comment] 2022-02-09 07:33
Thank you for your advice. Now the code  can output the kun-yomi, on-yomi, and meaning using the dict type as shown below. But I'm not confident about my code, because I assume the first part of [Entries] to be kun-yomi and the second part to be on-yomi. I'm really sorry.



![スクリーンショット 2022-02-09 16 31 13](https://user-images.githubusercontent.com/84693250/153142714-7abdfedb-79e4-46ae-a5da-b71d99b41f50.png)

![スクリーンショット 2022-02-09 16 30 42](https://user-images.githubusercontent.com/84693250/153142738-3e0b1043-

413d-4947-9a9a-76d505e71dcc.png)
![スクリーンショット 2022-02-09 16 30 08](https://user-images.githubusercontent.com/84693250/153142772-dc51cc2f-


![スクリーンショット 2022-02-09 16 29 33](https://user-images.githubusercontent.com/84693250/153142817-fa186bba-


ecfb-49c2-8b60-af3c43a2e97b.png)
![スクリーンショット 2022-02-09 16 29 11](https://user-images.githubusercontent.com/84693250/153142860-7fc6a349-6287-4a83-adab-54d300c828ec.png)


498a-4b8d-b889-311dbcf44b44.png)
.

**Comment by TakumiHiraide** [comment] 2022-02-09 07:34
Thank you for your advice. Now the code can output the kun-yomi, on-yomi, and meaning using the dict type as shown below. But I'm not confident about my code, because I assume the first part of [Entries] to be kun-yomi and the second part to be on-yomi. I'm really sorry.
![スクリーンショット 2022-02-09 16 31 13](https://user-images.githubusercontent.com/84693250/153143009-058ef2f2-
7ed3-4db7-9b5f-7df766485350.png)

![スクリーンショット 2022-02-09 16 30 42](https://user-images.githubusercontent.com/84693250/153143048-efdb1ebd-4058-4e49-b69b-29520317f887.png)

![スクリーンショット 2022-02-09 16 30 08](https://user-images.githubusercontent.com/84693250/153143060-1ad4b798-0338-4108-b1fc-754b934469fb.png)

![スクリーンショット 2022-02-09 16 29 33](https://user-images.githubusercontent.com/84693250/153143078-4e8e1bb6-d83c-4dc1-9522-aeb6c2a42127.png)

**Comment by TakumiHiraide** [comment] 2022-02-09 07:35
Thank you for your advice. Now the code can output the kun-yomi, on-yomi, and meaning using the dict type as shown below. But I'm not confident about my code, because I assume the first part of [Entries] to be kun-yomi and the second part to be on-yomi. I'm really sorry
![スクリーンショット 2022-02-09 16 31 13](https://user-images.githubusercontent.com/84693250/153143225-6976cff5-2f6d-4360-af01-56a49a786b73.png)
.

**Comment by TakumiHiraide** [comment] 2022-02-09 07:36
![スクリーンショット 2022-02-09 16 30 42](https://user-images.githubusercontent.com/84693250/153143262-92f21425-6e79-479c-99e3-a08054cc86e6.png)

![スクリーンショット 2022-02-09 16 30 08](https://user-images.githubusercontent.com/84693250/153143281-23f2bb0c-7bb7-4930-81de-a574bd3a2ecc.png)

![スクリーンショット 2022-02-09 16 29 33](https://user-images.githubusercontent.com/84693250/153143302-9f09b0e2-43a4-432e-b102-6cd119c9e5f4.png)

![スクリーンショット 2022-02-09 16 29 11](https://user-images.githubusercontent.com/84693250/153143335-2385746a-fcc8-4de9-9511-ae735fbab5ac.png)

**Comment by TakumiHiraide** [comment] 2022-02-09 07:37
![スクリーンショット 2022-02-09 16 28 06](https://user-images.githubusercontent.com/84693250/153143501-0b37455e-d48d-453b-9792-c4195127c292.png)

![スクリーンショット 2022-02-09 16 28 49](https://user-images.githubusercontent.com/84693250/153143516-16eaba0c-39a1-4d2f-9130-adcbefc2caab.png)

**Comment by ani-hovhannisyan** [comment] 2022-02-18 06:48
We've doen pair programmign with Hiraide san and Ihara san. And fixed local environment issues, not all works fine.

**Closed by ani-hovhannisyan** 2022-02-18 06:48 UTC
Labels: bug, coding, backend
